USE chat_app;

CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    passwd VARCHAR(50) NOT NULL
);

CREATE TABLE messages(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    message VARCHAR(250),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
)